# Generated by Django 5.2.6 on 2025-09-13 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=66)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_log', to='approvals.approval')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blockchain Log',
                'verbose_name_plural': 'Blockchain Logs',
                'ordering': ['-date_logged'],
            },
        ),
    ]
