# Generated by Django 4.2 on 2025-08-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='eth_address',
            new_name='wallet_address',
        ),
    ]
