# Generated by Django 5.2.6 on 2025-09-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
