# Generated by Django 5.2.6 on 2025-09-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blockchain_address',
            field=models.CharField(blank=True, help_text='Ethereum address for blockchain interactions', max_length=42, null=True, verbose_name='Blockchain Address'),
        ),
    ]
