# Generated by Django 5.2.6 on 2025-09-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_blockchain_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_personal_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
