# Generated by Django 5.2.6 on 2025-09-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('OFFICE_SUPPLIES', 'Office Supplies'), ('LAB_EQUIPMENT', 'Laboratory Equipment'), ('ICT_EQUIPMENT', 'ICT Equipment'), ('FURNITURE', 'Furniture'), ('CLEANING_MATERIALS', 'Cleaning Materials'), ('OTHERS', 'Others')], default='OTHERS', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
