# Generated by Django 5.2.6 on 2025-09-13 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('reason', models.TextField(help_text='Justification for the request and its priority.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review by Stores'), ('APPROVED', 'Approved by Stores'), ('REJECTED', 'Rejected by Stores')], default='PENDING', max_length=10)),
                ('stores_comment', models.TextField(blank=True, help_text='Comments from the Stores Manager upon approval/rejection.')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='inventory.product')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_requested'],
            },
        ),
    ]
