# Generated by Django 4.2 on 2025-07-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_damagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='department',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
