# Generated by Django 4.2 on 2025-08-18 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_stockrequest_department_stockrequest_urgent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='moved_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='damagereport',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='damagereport',
            name='reported_at',
        ),
        migrations.RemoveField(
            model_name='damagereport',
            name='reported_by',
        ),
        migrations.AddField(
            model_name='damagereport',
            name='reporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reported_damages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='severity',
            field=models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stockitem'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stockitem'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='moved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SupplierDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('verified', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(through='inventory.DeliveryItem', to='inventory.stockitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplierdelivery'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockitem'),
        ),
    ]
