# Generated by Django 4.2 on 2025-08-18 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_damagereport_quantity_damagereport_reported_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damagereport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Damage Report', 'verbose_name_plural': 'Damage Reports'},
        ),
        migrations.RemoveField(
            model_name='damagereport',
            name='reported_by',
        ),
        migrations.AddField(
            model_name='damagereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='damagereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_damages', to=settings.AUTH_USER_MODEL),
        ),
    ]
